// Flutter Agentation — public barrel.
export 'src/annotation/annotation_manager.dart';
export 'src/annotation/feedback_field.dart';
export 'src/context/context_model.dart';
export 'src/context/geometry.dart';
export 'src/context/source_location.dart';
export 'src/context/visual_changes.dart';
export 'src/exporter/clipboard_service.dart';
export 'src/exporter/json_exporter.dart';
export 'src/exporter/markdown_exporter.dart';
export 'src/exporter/widgets/copy_button.dart';
export 'src/overlay/agentation_controller.dart';
export 'src/overlay/agentation_overlay.dart';
export 'src/overlay/info_panel.dart';
export 'src/overlay/selection_highlight.dart';
export 'src/overlay/tokens.dart';
export 'src/resolver/widget_resolver.dart';
export 'src/selection/selection_engine.dart';
export 'src/selection/selection_result.dart';
